name: Validate Requirements

on:
  push:
    paths:
      - 'src/pyproject.toml'
      - 'src/requirements.txt'
  pull_request:
    paths:
      - 'src/pyproject.toml'
      - 'src/requirements.txt'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      
      - name: Install uv
        run: |
          curl -LsSf https://astral.sh/uv/install.sh | sh
          echo "$HOME/.cargo/bin" >> $GITHUB_PATH
      
      - name: Generate requirements.txt
        working-directory: ./src
        run: |
          uv pip compile pyproject.toml -o requirements.tmp.txt
      
      - name: Compare requirements files
        working-directory: ./src
        run: |
          if ! diff -q requirements.txt requirements.tmp.txt > /dev/null; then
            echo "ERROR: requirements.txt is out of sync with pyproject.toml"
            echo "Please run 'make requirements' in the src directory to update it"
            diff requirements.txt requirements.tmp.txt || true
            exit 1
          fi
          echo "requirements.txt is up to date"